---
title: "R Notebook"
output: html_notebook
---
https://www.analyticsvidhya.com/blog/2017/01/t-sne-implementation-r-python/
https://www.r-bloggers.com/playing-with-dimensions-from-clustering-pca-t-sne-to-carl-sagan/
```{r}
train <- read.csv("meninas.csv", stringsAsFactors=FALSE, sep=",")
train = train[,4:18]
train
```

cada vez q roda, gera valores diferentes, embora similares

```{r}
## calling the installed package
library(Rtsne)
## Curating the database for analysis with both t-SNE and PCA
Labels<-train$Forma.de.saída.da.opção
train$Forma.de.saída.da.opção<-as.factor(train$Forma.de.saída.da.opção)
## for plotting
colors = rainbow(length(unique(train$Forma.de.saída.da.opção)))
names(colors) = unique(train$Forma.de.saída.da.opção)

## Executing the algorithm on curated data
tsne <- Rtsne(train, dims = 2, perplexity=50, verbose=TRUE, max_iter = 500, check_duplicates = FALSE)
#exeTimeTsne<- system.time(Rtsne(train[,4:18], dims = 2, perplexity=10, verbose=TRUE, max_iter = 500, check_duplicates = FALSE))
## Plotting
plot(tsne$Y, t='n', main="tsne")
text(tsne$Y, col=colors[train$Forma.de.saída.da.opção])
```

```{r}

```







